### ISSUE TITLE
Error en el Game Over

### ISSUE THREAD

**Issue by FranRebe** [PioIX/2024-TPFinal-G02#1]
Cuando paso entre las estructuras, aparece la pantalla toda roja diciendo que colisionaste.

**Comment by jpradinho021206** [comment]
Cambie el ajuste del const gap haciendo que si pasa por el medio funcione y no ponga pantalla roja

**Comment by jpradinho021206** [comment]
Cambie el ajuste del const gap haciendo que si pasa por el medio funcione y no ponga pantalla roja
