### ISSUE TITLE
GameOver

### ISSUE THREAD

**Issue by velozo22** [PioIX/2024-TPFinal-G02#5]
Cada vez que el flappy pierde y al momento de clickear en la pantalla del game over se suma puntos

**Comment by FranRebe** [comment]
Puse un codigo que hace que solo permita saltar si no a perdido el jugador:
const handleClick = () => {
    if (!gameOver) { // Solo permitir saltar si el juego no ha terminado
      jump();
    }
  };

  useEffect(() => {
    window.addEventListener('click', handleClick);
    return () => {
      window.removeEventListener('click', handleClick);
    };
  }, [gameOver]);
