### ISSUE TITLE
VelocidadObstaculo

### ISSUE THREAD

**Issue by velozo22** [PioIX/2024-TPFinal-G02#6]
Cada vez que el flappy pasa por un obstaculo, se sube la velocidad (Deberia ser cada 3 obstaculos)

**Comment by FranRebe** [comment]
Cambie y mejore el codigo:
if (obstaclesPassed > 0 && obstaclesPassed % 3 === 0 && !speedIncreased) {
        setSpeed((prevSpeed) => prevSpeed + 0.5); // Aumentar la velocidad
        setSpeedIncreased(true); // Marcar que ya se ha aumentado la velocidad
      }

      if (obstaclesPassed % 3 !== 0) {
        setSpeedIncreased(false); // Restablecer la bandera de velocidad cuando no se ha pasado 3 obstáculos
      }
    };
